apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blog-app.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 "host" }}
      http:
        paths:
          - path: {{ index (index .Values.ingress.hosts 0 "paths") 0 "path" }}
            pathType: {{ index (index .Values.ingress.hosts 0 "paths") 0 "pathType" }}
            backend:
              service:
                name: {{ include "blog-app.fullname" . }}
                port:
                  number: 80