apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog-app.fullname" . }}
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8000
  selector:
    {{- include "blog-app.selectorLabels" . | nindent 4 }}
